@startuml RDCU redemarrerJeu
skinparam style strictuml
skinparam defaultfontname Verdana
skinparam backgroundcolor white
title RDCU pour redémarrerJeu
participant ":JeuDeDes" as jeu
participant "joueurs:\nMap<String, Joueur>" as joueurs
-> jeu : redemarrerJeu()
note right: selon Contrôleur\n(JeuDeDés est\nl'objet racine)
jeu -> joueurs : clear()
note right: selon Expert
@enduml